Handle additional edge cases for `evalConstantExpr()`
Consensys/solc-typed-ast pull request #230
Opened 2023-10-19 06:56 UTC by blitz-1306

## Changes
- [x] Support `Buffer` values (for hex literals) in unary math ops.
- [x] Introduce `fixedBytesTypeToIntType()`.
- [x] Add relaed test cases.

Regards.

2023-10-19 07:13 UTC, blitz-1306 commented on test/unit/types/eval_const.spec.ts
> +        // ],
@cd1m0 This is actually interesting and I might need help here.

Currently we apply `clampIntToType()` when type of `BinaryOperation` is `IntType`. However in this case we have `BoolType`, so result is not clamped. Other thing here is that two operands are casted to a common type, that is smaller, than type, that is computed by `InferType.inferCommonType()`, that is relying on `castable()`. In `castable()` we have following entry: https://github.com/Consensys/solc-typed-ast/blob/d4dd707aeb1ecff2627893e26e4c6ae1d6fce286/src/types/utils.ts#L431-L434

But in these cases:
```solidity
bytes2(0xcc00) < byte(0xee);
bytes2(0xff00) == byte(0xff);
```
it seems that result is coerced to a smaller size and this is fine even in latest compilers. I tried following:
```typescript
export function evalBinary(node: BinaryOperation, inference: InferType): Value {
    try {
        const leftT = inference.typeOf(node.vLeftExpression);
        const rightT = inference.typeOf(node.vRightExpression);
        const commonT = inference.inferCommonType(leftT, rightT);

        let left = evalConstantExpr(node.vLeftExpression, inference);
        let right = evalConstantExpr(node.vRightExpression, inference);

        if (commonT instanceof FixedBytesType) {
            left = clampIntToType(toInt(left), fixedBytesTypeToIntType(commonT));
            right = clampIntToType(toInt(right), fixedBytesTypeToIntType(commonT));
        }

        const res = evalBinaryImpl(node.operator, left, right);

        if (leftT instanceof NumericLiteralType && rightT instanceof NumericLiteralType) {
            return res;
        }

        const resT = inference.typeOfBinaryOperation(node);

        if (resT instanceof IntType && typeof res === "bigint") {
            return clampIntToType(res, resT);
        }

        return res;
    } catch (e: unknown) {
        if (e instanceof EvalError && e.expr === undefined) {
            e.expr = node;
        }

        throw e;
    }
}
```
But it solves only one case of two. Would you be able to find some time and take a look?

2023-10-24 06:53 UTC, blitz-1306 commented on test/unit/types/eval_const.spec.ts
> +        // ],
Addressed in d22f7d6

2023-10-24 20:01 UTC, cd1m0 requested changes
One nit. Will fix

2023-10-24 20:02 UTC, cd1m0 commented on src/types/eval_const.ts
> +        const res = evalUnaryImpl(node.operator, evalConstantExpr(node.vSubExpression, inference));
Fixed in [6269c0b](https://github.com/Consensys/solc-typed-ast/pull/230/commits/6269c0b303aaf68db07ef6e402c207fc8920a366)

2023-10-24 20:03 UTC, cd1m0 approved these changes

2023-10-24 21:03 UTC, merged