Refactor getter typing logic and canonical signatures logic
ConsenSys/solc-typed-ast pull request #70
Opened 2021-09-28 07:33 UTC by cd1m0

- Separate abi encoding logic in abi.ts;
- Move getterArgsAndReturn into VariableDeclaration class;
- Reduce code duplciation between getterArgsAndReturn and getterCanonicalSignature;
- Add `signature.spec.ts` tests that compare the canonical types/signatures with the function hashes and ABI the compiler outputs
- Make ABIEncoder a required argument for all `canonicalSignature` entry points in all classes that have them. (WARNING: This is an API breaking change)

2021-09-29 08:00 UTC, blitz-1306 requested changes
Goot job. Just a few things to tweak / polish.

2021-09-29 21:41 UTC, cd1m0 commented on src/ast/definitions.ts
> +                    // Its a safe to assume V2 as its abackward-compatible and
Addressed in ed393c6.

2021-09-29 21:41 UTC, cd1m0 commented on src/ast/definitions.ts
> +                    // Its a safe to assume V2 as its abackward-compatible and
Addressed in ed393c6.

2021-09-29 21:41 UTC, cd1m0 commented on src/ast/implementation/declaration/variable_declaration.ts
> +            "Called getterArgsAndReturn() on variable thisaration without type",
Addressed in ed393c6.

2021-09-29 21:42 UTC, cd1m0 commented on src/bin/compile.ts
> +        const encoderVersion = getABIEncoderVersion(units, result.compilerVersion as string);
Fixed it to not print signatures/interface ids when there is no known compiler version. Addressed in ed393c6.

2021-09-29 21:42 UTC, cd1m0 commented on test/samples/solidity/getters_08.sol
> -}
Addressed in ed393c6.

2021-09-29 21:42 UTC, cd1m0 commented on test/samples/solidity/getters_07_abiv1.sol
> +        Some t = this.f(0);
Addressed in ed393c6.

2021-09-29 21:42 UTC, cd1m0 commented on test/samples/solidity/getters_07_abiv1.sol
> +}
Addressed in ed393c6.

2021-09-30 03:47 UTC, blitz-1306 approved these changes
Looks good.

2021-09-30 03:49 UTC, merged